"""
p2mem.petrophysics_models - Typed data structures for the Increment 6
gamma-ray QC, endpoint-sensitivity, and screening-proxy layer.

Scientific boundary encoded in these types
------------------------------------------
Every quantity defined here is either a FACTUAL MEASUREMENT SUMMARY of a
gamma-ray-family curve, or a DIMENSIONLESS SCREENING PROXY derived from
one under explicitly assumed, configured endpoints. Nothing here is a
calibrated shale volume, and nothing here is a lithology.

The naming is deliberate and load-bearing:

* `GrEndpointScenario.gr_low_endpoint_api` / `gr_high_endpoint_api` are
  ASSUMED values produced by a configured percentile rule. The field
  `evidence_class` on every scenario is `"assumed_configured"` and there
  is no code path in this project that can set it to anything stronger.
* `GrProxyResult.igr_unclipped_frac` is retained beside
  `igr_clipped_frac` so the amount of clipping - i.e. how far the real
  data fell outside the assumed bracket - is always visible.
* The linear proxy field is named `VSH_GR_linear_proxy_frac`: the word
  "proxy" is part of the identifier itself, so the quantity cannot be
  referenced anywhere downstream without carrying its own disclaimer.
  It is never named `VSH`, `Vshale`, or `shale_volume`.

Confidence classes (`GR_PROXY_HIGH` and friends) describe DATA AND PROXY
CONFIDENCE ONLY. Every class string generated by this layer is checked
against `p2mem.wellframe_models.PROHIBITED_LITHOLOGY_TERMS`.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Optional, Tuple

import numpy as np

__all__ = [
    "USE_STATUS_PROXY_ALLOWED",
    "USE_STATUS_PROXY_ALLOWED_DEPTH_TIED",
    "USE_STATUS_QC_ONLY_EXCLUDED",
    "VALID_USE_STATUSES",
    "PROXY_PERMITTED_USE_STATUSES",
    "EXCLUSION_REASON_BOREAS_ECGR",
    "GR_PROXY_HIGH",
    "GR_PROXY_INTERMEDIATE",
    "GR_PROXY_LOW",
    "GR_NOT_AVAILABLE",
    "GR_EXCLUDED_UNRESOLVED_SCALE",
    "VALID_GR_CONFIDENCE_CLASSES",
    "GrFamilyDisposition",
    "GrFamilyQcStats",
    "GrEndpointScenario",
    "GrProxyResult",
    "PetrophysicsIssue",
    "PetrophysicsEligibilityConfig",
]

# ---------------------------------------------------------------------------
# GR-family use-status vocabulary
# ---------------------------------------------------------------------------
USE_STATUS_PROXY_ALLOWED = "screening_proxy_allowed"
USE_STATUS_PROXY_ALLOWED_DEPTH_TIED = "screening_proxy_allowed_depth_tied"
USE_STATUS_QC_ONLY_EXCLUDED = "qc_only_excluded"

VALID_USE_STATUSES: Tuple[str, ...] = (
    USE_STATUS_PROXY_ALLOWED,
    USE_STATUS_PROXY_ALLOWED_DEPTH_TIED,
    USE_STATUS_QC_ONLY_EXCLUDED,
)

# The ONLY two statuses under which any GR-derived quantity may be computed.
# A well whose status is not in this tuple gets no GR index, no proxy, no
# flag, no lithology-dependent mask, and no NCT-donor status - enforced in
# `p2mem.petrophysics` and re-checked by the test suite.
PROXY_PERMITTED_USE_STATUSES: Tuple[str, ...] = (
    USE_STATUS_PROXY_ALLOWED,
    USE_STATUS_PROXY_ALLOWED_DEPTH_TIED,
)

EXCLUSION_REASON_BOREAS_ECGR = "BOREAS_ECGR_SCALE_UNRESOLVED"

# ---------------------------------------------------------------------------
# Data/proxy confidence classes - NEVER lithology classes
# ---------------------------------------------------------------------------
GR_PROXY_HIGH = "GR_PROXY_HIGH"
GR_PROXY_INTERMEDIATE = "GR_PROXY_INTERMEDIATE"
GR_PROXY_LOW = "GR_PROXY_LOW"
GR_NOT_AVAILABLE = "GR_NOT_AVAILABLE"
GR_EXCLUDED_UNRESOLVED_SCALE = "GR_EXCLUDED_UNRESOLVED_SCALE"

VALID_GR_CONFIDENCE_CLASSES: Tuple[str, ...] = (
    GR_PROXY_HIGH,
    GR_PROXY_INTERMEDIATE,
    GR_PROXY_LOW,
    GR_NOT_AVAILABLE,
    GR_EXCLUDED_UNRESOLVED_SCALE,
)


@dataclass(frozen=True)
class GrFamilyDisposition:
    """
    One well's human-authored gamma-ray-family disposition, read verbatim
    from `config/petrophysics_eligibility.yml`.

    This object is never inferred from data. `use_status` and
    `exclusion_reason` are review decisions; the code's only job is to
    honour them exactly and to refuse to compute anything a
    `qc_only_excluded` status forbids.
    """

    well_key: str
    source_las_filename: str
    gr_family_canonical_name: str
    gr_family_source_curve_name: str
    use_status: str
    exclusion_reason: Optional[str]
    evidence_class: str
    has_approved_formation_tops: bool
    notes: str = ""

    def __post_init__(self) -> None:
        if self.use_status not in VALID_USE_STATUSES:
            raise ValueError(
                f"GrFamilyDisposition {self.well_key!r}: use_status {self.use_status!r} is not one "
                f"of {VALID_USE_STATUSES}."
            )
        if self.use_status == USE_STATUS_QC_ONLY_EXCLUDED and not self.exclusion_reason:
            raise ValueError(
                f"GrFamilyDisposition {self.well_key!r}: a 'qc_only_excluded' well must carry a "
                f"machine-readable exclusion_reason; an unexplained exclusion is not auditable."
            )

    @property
    def proxy_permitted(self) -> bool:
        """True only when this well's configured status permits any
        GR-derived calculation at all."""
        return self.use_status in PROXY_PERMITTED_USE_STATUSES


@dataclass(frozen=True)
class GrFamilyQcStats:
    """
    Purely factual, non-judgemental statistics for one well's GR-family
    curve. Computed for EVERY well - including a `qc_only_excluded` one,
    because factual QC reporting is exactly what an excluded well remains
    available for.

    `n_samples_above_seabed` is Optional: it is a genuine integer only for
    a well whose seabed marker exists in the LOCKED Increment 5
    survey-corrected output. For a well with no approved formation tops it
    is None, meaning "not determinable from approved data" - never 0, which
    would falsely assert that no such samples exist.
    """

    well_key: str
    gr_family_canonical_name: str
    gr_family_source_curve_name: str
    source_las_filename: str
    unit: str
    n_samples: int
    valid_count: int
    valid_fraction: float
    min_api: Optional[float]
    max_api: Optional[float]
    median_api: Optional[float]
    p01_api: Optional[float]
    p05_api: Optional[float]
    p10_api: Optional[float]
    p25_api: Optional[float]
    p50_api: Optional[float]
    p75_api: Optional[float]
    p90_api: Optional[float]
    p95_api: Optional[float]
    p99_api: Optional[float]
    dynamic_range_p05_p95_api: Optional[float]
    n_negative_samples: int
    n_zero_samples: int
    n_samples_above_seabed: Optional[int]
    seabed_basis: str
    n_valid_blocks: int
    longest_valid_block_samples: int
    longest_missing_block_samples: int
    longest_missing_block_md_start_m: Optional[float]
    longest_missing_block_md_end_m: Optional[float]
    statistics_basis: str


@dataclass(frozen=True)
class GrEndpointScenario:
    """
    One well's MEASURED endpoint values under one configured scenario.

    `gr_low_endpoint_api` / `gr_high_endpoint_api` are the values the
    scenario's percentile rule actually produced when applied to THIS
    well's own valid, depth-mapped samples. They are recorded so that a
    reader can see the numbers the rule generated, not merely the rule.

    `evidence_class` is fixed at `"assumed_configured"`. There is no
    constructor path, config key, or code branch anywhere in this project
    that can promote an endpoint scenario to a calibrated status.
    """

    well_key: str
    scenario_name: str
    low_percentile: float
    high_percentile: float
    gr_low_endpoint_api: float
    gr_high_endpoint_api: float
    endpoint_separation_api: float
    n_samples_used_for_endpoints: int
    endpoint_sample_basis: str
    description: str
    evidence_class: str = "assumed_configured"
    calibration_status: str = "uncalibrated_assumed_no_calibration_data_exists"


@dataclass(frozen=True)
class GrProxyResult:
    """
    One well's GR-index and linear screening-proxy arrays under ONE
    endpoint scenario.

    All arrays are full-length and aligned sample-for-sample with the well
    frame's `MD_m`. A sample that is invalid (non-finite GR, or an
    unmapped depth) is NaN in every array and False in `valid_mask` - it
    is never filled, interpolated, or dropped, so array positions remain
    directly comparable with the well frame and with other scenarios.

    `igr_unclipped_frac` may legitimately fall outside [0, 1]: that is the
    honest signal that the well's real data exceeded the assumed endpoint
    bracket, and `n_clipped_low` / `n_clipped_high` quantify it.

    `VSH_GR_linear_proxy_frac` is numerically identical to
    `igr_clipped_frac` under this increment's only permitted transform
    (linear identity). It is carried as a separately named array anyway,
    because the two mean different things: one is a normalized curve
    position, the other is the quantity a later increment might be tempted
    to treat as a shale volume - and the name is the guardrail.
    """

    well_key: str
    scenario_name: str
    gr_family_canonical_name: str
    gr_low_endpoint_api: float
    gr_high_endpoint_api: float
    igr_unclipped_frac: np.ndarray
    igr_clipped_frac: np.ndarray
    VSH_GR_linear_proxy_frac: np.ndarray
    valid_mask: np.ndarray
    n_valid: int
    n_clipped_low: int
    n_clipped_high: int
    clipped_fraction: float
    proxy_median: Optional[float]
    proxy_p25: Optional[float]
    proxy_p75: Optional[float]
    transform_name: str = "linear_identity_of_clipped_igr"
    calibration_status: str = "screening_proxy_uncalibrated_not_a_shale_volume"


@dataclass(frozen=True)
class PetrophysicsIssue:
    """
    One reportable fact about the Increment 6 petrophysics layer, mirroring
    the LOCKED `IngestionIssue` shape (severity / code / message / context)
    so that every increment's issue tables stay structurally comparable.
    """

    severity: str  # "ERROR" | "WARNING" | "INFO"
    code: str
    message: str
    context: str


@dataclass(frozen=True)
class PetrophysicsEligibilityConfig:
    """
    The fully parsed, validated contents of
    `config/petrophysics_eligibility.yml`.

    Held as a typed object rather than a raw dict so that a missing or
    misspelled key fails loudly at load time - at the one place a human
    can fix it - instead of silently defaulting deep inside a calculation.
    """

    schema_version: str
    increment: int
    assurance_tier: str
    policy: Dict
    endpoint_scenarios: Tuple[Dict, ...]
    wells: Dict[str, GrFamilyDisposition]
    gr_proxy_confidence: Dict
    method_eligibility: Dict
    source_filename: str = ""
    raw_policy_notes: Tuple[str, ...] = field(default_factory=tuple)

    @property
    def scenario_names(self) -> Tuple[str, ...]:
        return tuple(str(s["scenario_name"]) for s in self.endpoint_scenarios)
